sdg-data-canada-odd-donnees/cif-data-donnees-cic

meta/3-13-1.md, meta/3-3-1.md, meta/5-3-1.md, meta/fr/3-12-1.md, meta/fr/3-13-1.md, meta/fr/3-3-1.md, meta/fr/5-2-1.md, meta/fr/5-3-1.md, meta/fr/6-1-1.md, meta/fr/6-2-1.md, meta/fr/6-3-1.md, meta/fr/6-4-1.md, translations/fr/data.yml
Updates to various indicators' metadata based on feedback.
=> Metadata updates

CIFProgressStatus.py, data/indicator_3-2-1.csv, meta/15-4-1.md, meta/16-3-1.md, meta/3-2-1.md, meta/9-3-1.md, meta/fr/3-2-1.md, scripts/requirements.txt
=> Add historical data for 3.2.1

R/indicator_8.6.1.R, data/indicator_6-1-1.csv, meta/8-6-1.md, meta/fr/8-6-1.md
- Issue #201
- Added automation script for new CODR table 36-10-0681-01.
- Updated metadata and data source.
- Issue #203
- Updated with new data.
=> More updates

meta/16-6-1.md, meta/fr/16-6-1.md
=> CIF Review 16.6.1

meta/16-5-1.md, meta/fr/16-5-1.md, translations/en/global_targets.yml, translations/fr/global_targets.yml
=> CIF Review 16.5.1

translations/en/global_targets.yml, translations/fr/global_targets.yml
- #288 
- Removed note and * for ambition 16.6 on Goal 16 page
=> CIF Review 16.6.1 - Part 2

R/indicator_16-1-1.R, data/indicator_16-1-1.csv, meta/16-1-1.md, meta/fr/16-1-1.md, translations/en/data.yml, translations/fr/data.yml
- #282
- Removed data/metadata related to old data sources (General Social Survey)
- Added automated script
- Updated data, metadata, and translation files
=> CIF Review 16.1.1

meta/16-1-1.md, meta/fr/16-1-1.md, translations/fr/data.yml
- #282 
- Changed graph type to bar chart since there is only one year of data at the moment.
- Selected some data to display on graph by default
=> CIF Review 16.1.1 - Part 2

R/indicator_1-3-1.R, data/indicator_1-3-1.csv, meta/1-3-1.md, meta/fr/1-3-1.md, translations/en/data.yml, translations/en/general.yml, translations/en/global_targets.yml, translations/fr/data.yml, translations/fr/general.yml, translations/fr/global_targets.yml
https://github.com/sdg-data-canada-odd-donnees/cif-data-donnees-cic/issues/224#issue-2331409380
1. Added an R script to update data automatically for Indicator 1.3.1
2. Populated French and English metadata files
3. Added translations for ambition and target in French and in English
4. Updated translation files with new terms from the Statistics Canada data source
**Miscellaneous :** 
- Updated any reference to Twitter to "X (formerly Twitter)" as part of organization policies
=> CIF Review 1.3.1: New Indicator Created

meta/3-1-1.md, meta/fr/3-1-1.md, translations/en/data.yml, translations/en/global_targets.yml, translations/fr/data.yml, translations/fr/global_targets.yml
https://github.com/sdg-data-canada-odd-donnees/cif-data-donnees-cic/issues/226
- Updated Indicator 3.1.1's target within the metadata files and translation files
**Miscellaneous:**
- Added missing translation keys in French and English for indicator 1.3.1
=> CIF Review 3.1.1: Target Update

meta/3-3-1.md, meta/fr/3-3-1.md, translations/en/global_targets.yml, translations/fr/global_targets.yml
https://github.com/sdg-data-canada-odd-donnees/cif-data-donnees-cic/issues/234
- Updated indicator name and target within the metadata files
- Updated translation files with the new target
=> CIF Review 3.3.1: Update Indicator Name and Target

R/indicator_3-4-1.R, data/indicator_3-4-1.csv, meta/3-4-1.md, meta/fr/3-4-1.md, translations/en/data.yml, translations/en/global_targets.yml, translations/fr/data.yml, translations/fr/global_targets.yml
https://github.com/sdg-data-canada-odd-donnees/cif-data-donnees-cic/issues/235
- Updated Indicator 3.4.1's metadata files with new, up-to-date information (indicator title, description, target, data source, progress measure)
- Updated R script with new data source
- Updated CSV file with new data
- Updated translation files with new target and terms from data source
=> CIF Review 3.4.1: Update Indicator

meta/16-3-1.md, meta/fr/16-3-1.md
- #285 
- Edited graph units to "Rate per 100,000 population" / "Taux pour 100 000 habitants"
=> CIF Review - Move 16.4.1 to 16.3.1 - Part 2

R/indicator_3-15-1.R, data/indicator_3-15-1.csv, meta/3-15-1.md, meta/fr/3-15-1.md, translations/en/global_targets.yml, translations/fr/global_targets.yml
https://github.com/sdg-data-canada-odd-donnees/cif-data-donnees-cic/issues/246
1. Added an R script to update data automatically for Indicator 3.15.1
2. Populated French and English metadata files
3. Added translations for ambition and target in French and in English
=> CIF Review 3.15.1: New Indicator Created

R/indicator_3-5-1.R, data/indicator_3-5-1.csv, meta/3-5-1.md, meta/fr/3-5-1.md, translations/en/global_targets.yml, translations/fr/global_targets.yml
https://github.com/sdg-data-canada-odd-donnees/cif-data-donnees-cic/issues/236
1. Added an R script to update data automatically for Indicator 3.5.1
2. Populated French and English metadata files
3. Added translations for ambition and target in French and in English
=> CIF Review 3.5.1: New Indicator Created

R/indicator_4-3-1.R, data/indicator_4-3-1.csv, meta/3-10-1.md, meta/3-13-1.md, meta/3-15-1.md, meta/3-4-1.md, meta/3-5-1.md, meta/3-9-1.md, meta/4-3-1.md, meta/fr/3-10-1.md, meta/fr/3-4-1.md, meta/fr/3-5-1.md, meta/fr/3-9-1.md, meta/fr/4-3-1.md, translations/en/global_targets.yml, translations/fr/global_targets.yml
https://github.com/sdg-data-canada-odd-donnees/cif-data-donnees-cic/issues/247
1. Added an R script to update data automatically for Indicator 4.3.1
2. Populated French and English metadata files
3. Added translations for ambition and target in French and in English
**Miscellaneous:**
- Added missing progress measure status for Indicator 3.5.1
- Added data start values for Indicator 3.4.1, 3.13.1, and 3.15.1
- Changed wording for geographical coverage from "Province or territory" to "provinces and territories" for some indicators
- Corrected wording on notes for Indicator 3.9.1 and 3.10.1 
- Added note on progress measure for Indicator 3.5.1
=> CIF Review 4.3.1: New Indicator Created

meta/5-1-2.md, meta/fr/5-1-2.md, translations/en/global_targets.yml, translations/fr/global_targets.yml
https://github.com/sdg-data-canada-odd-donnees/cif-data-donnees-cic/issues/248
- Updated target in translation files
- Updated target in metadata files
=> CIF Review 5.1.2: Target Updated

R/indicator_16-4-1.R, data/indicator_16-4-1.csv, meta/16-4-1.md, meta/fr/16-4-1.md, translations/en/data.yml, translations/en/global_targets.yml, translations/fr/data.yml, translations/fr/global_targets.yml
=> CIF Review 16.4.1 - New indicator

translations/en/global_targets.yml, translations/fr/global_targets.yml
=> CIF Review 15.1.1 - Ambition update

R/indicator_6-3-1.R, data/indicator_6-3-1.csv, meta/6-3-1.md, meta/fr/6-3-1.md, translations/en/data.yml, translations/fr/data.yml
https://github.com/sdg-data-canada-odd-donnees/cif-data-donnees-cic/issues/251
**Issues fixed:** 
- Updated metadata files to include new source and method of computation
- Updated R script to calculate water use per capita growth rate
- Updated data file
=> CIF Review 6.3.1: Indicator Updated

meta/15-2-1.md, meta/fr/15-2-1.md, translations/en/global_targets.yml, translations/fr/global_targets.yml
=> CIF Review 15.2.1 - Ambition and target update

meta/7-1-1.md, meta/fr/7-1-1.md
https://github.com/sdg-data-canada-odd-donnees/cif-data-donnees-cic/issues/253
**Issues fixed:** 
- Updated indicator name in metadata files
=> CIF Review 7.1.1: Indicator Name Updated

R/indicator_7-2-1.R, R/indicator_7-3-1.R, data/indicator_7-2-1.csv, data/indicator_7-3-1.csv, meta/7-2-1.md, meta/7-3-1.md, meta/fr/7-2-1.md, meta/fr/7-3-1.md, translations/en/data.yml, translations/en/global_targets.yml, translations/fr/data.yml, translations/fr/global_targets.yml
https://github.com/sdg-data-canada-odd-donnees/cif-data-donnees-cic/issues/254
- Updated metadata files
- Updated CSV files
- Renamed R scripts
=> CIF Review 7.2.1: Indicator Number Switched with 7.3.1

meta/7-2-1.md, meta/fr/7-2-1.md, translations/en/global_targets.yml, translations/fr/global_targets.yml
https://github.com/sdg-data-canada-odd-donnees/cif-data-donnees-cic/issues/255
- Updated Indicator number to 7.2.1
- Updated metadata files with new indicator name and target
- Updated translation files with new target
=> CIF Review 7.3.1: Indicator Updated

data/indicator_15-3-1.csv, meta/15-3-1.md, meta/fr/15-1-1.md, meta/fr/15-2-1.md, meta/fr/15-3-1.md, translations/en/data.yml, translations/en/global_targets.yml, translations/fr/data.yml, translations/fr/global_targets.yml
- #278 
- Only showing data >= 2015
- Combined species group-based indices and system-based indices into a single tidy database
=> CIF Review 15.3.1 - New indicator

R/indicator_8-2-1.R, data/indicator_8-2-1.csv, meta/8-2-1.md
**Issues fixed:** 
- Added data start values to display data properly on the graph
- Updated R script to rename certain age groups and reorder geography
=> CIF Review 8.2.1: Fixed data display issues

meta/2-1-1.md, meta/fr/2-1-1.md
https://github.com/sdg-data-canada-odd-donnees/cif-data-donnees-cic/issues/344
Updated graph title
=> CIF Review 2.1.1: Changed graph title

meta/8-6-1.md, meta/fr/8-6-1.md, translations/en/global_targets.yml, translations/fr/global_targets.yml
https://github.com/sdg-data-canada-odd-donnees/cif-data-donnees-cic/issues/257
- Updated targets in translation files
- Updated targets in metadata files
- Added target and target year for progress measure
=> CIF Review 8.6.1: Updated Target

R/indicator_9-1-1.R, data/indicator_9-1-1.csv, meta/8-2-1.md, meta/9-1-1.md, meta/fr/8-2-1.md, meta/fr/9-1-1.md, translations/en/data.yml, translations/fr/data.yml
https://github.com/sdg-data-canada-odd-donnees/cif-data-donnees-cic/issues/258
- Updated metadata files with new source, indicator name, and description
- Created R script to update data automatically
- Updated data file with new data
**Miscellaneous:** 
- Added geographical coverage for 8.2.1
=> CIF Review 9.1.1: Indicator Updated

meta/9-3-1.md, meta/fr/9-3-1.md, translations/en/global_targets.yml, translations/fr/global_targets.yml
https://github.com/sdg-data-canada-odd-donnees/cif-data-donnees-cic/issues/260
- Target updated in metadata files
- Target updated in translation files
=> CIF Review 9.3.1: Target Updated

R/indicator_1-3-1.R, data/indicator_1-3-1.csv
https://github.com/sdg-data-canada-odd-donnees/cif-data-donnees-cic/issues/224#issuecomment-2248314790
=> Fixed R script that removed Wages and Salaries from the Main source of income column

meta/2-1-1.md
https://github.com/sdg-data-canada-odd-donnees/cif-data-donnees-cic/issues/344#issuecomment-2248336837
=> Updated the English indicator description to: "This indicator measures the prevalence of food insecurity."

R/indicator_3-4-1.R, data/indicator_3-4-1.csv, meta/3-4-1.md
https://github.com/sdg-data-canada-odd-donnees/cif-data-donnees-cic/issues/235#issuecomment-2248381037
=> Added map, updated data start values, and R script to include Total alcoholic beverages

meta/3-5-1.md, meta/fr/3-5-1.md
https://github.com/sdg-data-canada-odd-donnees/cif-data-donnees-cic/issues/236#issuecomment-2248403935
=> CIF Review 3.5.1: Added additional description in metadata files

R/indicator_3-7-1.R, data/indicator_3-7-1.csv, meta/fr/3-7-1.md, translations/en/data.yml, translations/fr/data.yml
https://github.com/sdg-data-canada-odd-donnees/cif-data-donnees-cic/issues/238#issuecomment-2248629441
=> CIF Review 3.7.1: Updated R script, CSV file, Metadata description, and data translation files

R/indicator_3-13-1.R, data/indicator_3-13-1.csv, meta/3-13-1.md, meta/fr/3-13-1.md, translations/en/data.yml, translations/fr/data.yml, translations/fr/global_targets.yml
https://github.com/sdg-data-canada-odd-donnees/cif-data-donnees-cic/issues/244#issuecomment-2248695462
=> CIF Review 3.13.1: Updated metadata files, progress measure, and data

R/indicator_3-15-1.R, data/indicator_3-15-1.csv, meta/3-13-1.md, meta/3-15-1.md, meta/fr/3-13-1.md, meta/fr/3-15-1.md
https://github.com/sdg-data-canada-odd-donnees/cif-data-donnees-cic/issues/246#issuecomment-2248750157
=> CIF Review 3.15.1: Updated data and metadata

meta/fr/7-1-1.md
https://github.com/sdg-data-canada-odd-donnees/cif-data-donnees-cic/issues/253#issuecomment-2250326892
=> CIF Review 7.1.1: Updated the indicator name in the French page of 7.1.1

meta/7-2-1.md, meta/7-3-1.md, meta/fr/7-2-1.md, meta/fr/7-3-1.md
https://github.com/sdg-data-canada-odd-donnees/cif-data-donnees-cic/issues/255#issue-2390883051
=> CIF Review 7.2.1: Updated target lines and data start values for 7.2.1 and 7.3.1

R/indicator_3-14-1.R, data/indicator_3-14-1.csv, meta/3-14-1.md, meta/3-4-1.md
https://github.com/sdg-data-canada-odd-donnees/cif-data-donnees-cic/issues/245#issuecomment-2248735701
=> CIF Review 3.14.1: Updated indicator name, default series, graph type, and R script

meta/4-3-1.md, meta/fr/4-3-1.md, translations/en/data.yml, translations/fr/data.yml
https://github.com/sdg-data-canada-odd-donnees/cif-data-donnees-cic/issues/247#issuecomment-2256800991
=> CIF Review 4.3.1: Updated metadata with comments and limitations and added maps to indicator page

meta/9-1-1.md, meta/9-3-1.md, meta/fr/9-1-1.md
https://github.com/sdg-data-canada-odd-donnees/cif-data-donnees-cic/issues/258#issuecomment-2250319735
https://github.com/sdg-data-canada-odd-donnees/cif-data-donnees-cic/issues/260#issuecomment-2250285633
=> CIF Review 9.1.1 and 9.3.1: Updated data start values, hyperlink text, fixed indentations, and added map

meta/16-4-1.md, meta/fr/16-4-1.md
https://github.com/sdg-data-canada-odd-donnees/cif-data-donnees-cic/issues/286#issuecomment-2252793514
=> CIF Review 16.4.1: Updated indicator metadata and set the limit of the Y axis to 100

meta/3-15-1.md, meta/fr/3-15-1.md, meta/fr/6-3-1.md, translations/fr/data.yml
https://github.com/sdg-data-canada-odd-donnees/cif-data-donnees-cic/issues/251#issuecomment-2260455169
https://github.com/sdg-data-canada-odd-donnees/cif-data-donnees-cic/issues/246#issuecomment-2260497603
=> CIF Review 6.3.1 and 3.15.1: Updated data translation files and metadata description

translations/en/global_targets.yml, translations/fr/global_targets.yml
https://github.com/sdg-data-canada-odd-donnees/cif-data-donnees-cic/issues/275
https://github.com/sdg-data-canada-odd-donnees/cif-data-donnees-cic/issues/276
=> CIF Review SDG 15: Reverted back to old ambitions for 15.1.1., 15.2.1, and 15.3.1

R/indicator_8-5-1.R, data/indicator_8-5-1.csv, meta/8-5-1.md, meta/fr/8-5-1.md
https://github.com/sdg-data-canada-odd-donnees/cif-data-donnees-cic/issues/351
- Updated R script to use "Chained (2017) dollars" instead of using "Current prices"
- Updated method of computation to reflect that change
=> CIF Review 8.5.1: Indicator Updated

.github/workflows/data_update.yml, .github/workflows/refresh-indicator-data.yml, .gitignore, R/indicator_9-6-1.R, automation_helper_functions.R, data/indicator_9-6-1.csv, meta/9-6-1.md, meta/fr/9-6-1.md, translations/en/data.yml, translations/en/global_targets.yml, translations/fr/data.yml, translations/fr/global_targets.yml
https://github.com/sdg-data-canada-odd-donnees/cif-data-donnees-cic/issues/261
- Updated metadata files with new target and indicator name
- Updated data start values and progress measure calculations
- Added map
- Updated R script to use the electric charging and alternative fuelling API, use GitHub secrets, and .env files
- Updated GitHub workflows to use environmental variables and GitHub secrets
- Updated translation files (target and data files)
- Updated CSV file
=> CIF Review 9.6.1: Indicator Updated

data/indicator_6-4-1.csv, meta/6-4-1.md, meta/fr/6-4-1.md
=> CIF Review - Various updates 6.4.1

translations/en/global_targets.yml, translations/fr/global_targets.yml
=> CIF Review - Ambitions update 15.1.1, 15.2.1, 15.3.1

R/indicator_11-5-1.R, R/indicator_5-2-1.R, automation_script.R, data/indicator_5-2-1.csv, meta/5-2-1.md, meta/fr/5-2-1.md, translations/en/data.yml, translations/fr/data.yml
https://github.com/sdg-data-canada-odd-donnees/cif-data-donnees-cic/issues/390
- Added R script to automate data updates for the indicator
- Updated CSV file
- Updated data translation files
- Updated metadata sources and data start values
**Miscellaneous fixes:**
- Updated automation script to run on all R scripts
- Removed write CSV on 11.5.1 temporarily as to not overwrite current dataset
=> CIF Review 5.2.1: Indicator Updated

R/indicator_9-6-1.R, meta/9-6-1.md, meta/fr/9-6-1.md, translations/en/data.yml, translations/en/global_targets.yml, translations/fr/data.yml
https://github.com/sdg-data-canada-odd-donnees/cif-data-donnees-cic/issues/261#issuecomment-2273821835
=> CIF Review 9.6.1: Updates R script, metadata, and data translation files

meta/15-5-1.md
- #280 
- update EN source link
=> CIF Review - 15.5.1 review

meta/fr/9-7-1.md, translations/en/data.yml, translations/fr/data.yml
https://github.com/sdg-data-canada-odd-donnees/cif-data-donnees-cic/issues/262#issuecomment-2277857475
=> CIF Review 9.7.1: Updated terms in data translation files and updated wording in metadata file

meta/3-13-1.md, meta/fr/3-13-1.md, translations/en/global_targets.yml, translations/fr/global_targets.yml
https://github.com/sdg-data-canada-odd-donnees/cif-data-donnees-cic/issues/244#issuecomment-2277924096
=> CIF Review 3.13.1: Updated metadata

R/indicator_10-2-1.R, data/indicator_10-2-1.csv, meta/10-2-1.md, meta/fr/10-2-1.md
https://github.com/sdg-data-canada-odd-donnees/cif-data-donnees-cic/issues/387
=> CIF Review 10.2.1: Updated metadata and created R script

meta/17-1-1.md, meta/fr/17-1-1.md, translations/fr/data.yml
- #290 
- now only displaying overall score by default
- changed "usage de données" to "utilisation de données"
- minor grammar correction in FR metadata
=> CIF Review - 17.1.1 review

.github/workflows/data_update.yml, .github/workflows/refresh-indicator-data.yml, R/indicator_17-3-1.R, data/indicator_17-3-1.csv, meta/17-3-1.md, meta/fr/17-3-1.md, translations/en/data.yml, translations/en/global_targets.yml, translations/fr/data.yml, translations/fr/global_targets.yml
=> CIF Review - New Indicator 17.3.1

meta/17-3-1.md, meta/fr/17-3-1.md, translations/en/data.yml, translations/fr/data.yml
- #291
- some minor wording changes in metadata and data fields
- added progress measure
- set start value: Environmental and clean technology products
=> CIF Review - New indicator 17.3.1 part 2

.github/workflows/special-char-test.yml, translations/en/data.yml, translations/fr/data.yml
some fixes for data fields that were not appearing correctly
=> Data field fixes

meta/11-5-1.md, meta/fr/11-5-1.md
https://github.com/sdg-data-canada-odd-donnees/cif-data-donnees-cic/issues/266
=> CIF review 11.5.1: Updated Indicator Name

R/indicator_11-2-1.R, data/indicator_11-2-1.csv, meta/11-2-1.md, meta/fr/11-2-1.md, translations/en/data.yml, translations/fr/data.yml
https://github.com/sdg-data-canada-odd-donnees/cif-data-donnees-cic/issues/350
- Updated metadata with new source and data start values
- Created R script for the new data source
- Updated CSV file
- Updated data translation files
=> CIF Review 11.2.1: Indicator Data Updated

meta/11-3-1.md, meta/fr/11-3-1.md, translations/en/global_targets.yml, translations/fr/global_targets.yml
https://github.com/sdg-data-canada-odd-donnees/cif-data-donnees-cic/issues/265
=> CIF Review 11.3.1: Updated Metadata

R/indicator_11-4-1.R, data/indicator_11-4-1.csv, meta/11-4-1.md, meta/fr/11-4-1.md
https://github.com/sdg-data-canada-odd-donnees/cif-data-donnees-cic/issues/386
=> CIF Review 11.4.1: Updated R Script

meta/11-6-1.md, meta/fr/11-6-1.md, translations/en/global_targets.yml, translations/fr/global_targets.yml
https://github.com/sdg-data-canada-odd-donnees/cif-data-donnees-cic/issues/267
=> CIF Review 11.6.1: Updated Target

meta/11-7-1.md, meta/fr/11-7-1.md
https://github.com/sdg-data-canada-odd-donnees/cif-data-donnees-cic/issues/268
=> CIF Review 11.7.1: Updated indicator name

data/indicator_11-1-1.csv, meta/11-1-1.md, meta/fr/11-1-1.md
https://github.com/sdg-data-canada-odd-donnees/cif-data-donnees-cic/issues/263#issuecomment-2296487253
=> CIF Review 11.1.1: Updated Progress Measure

CIFProgressStatus.py, R/indicator_14-2-1.R, data/indicator_14-2-1.csv, meta/14-2-1.md, meta/fr/14-2-1.md, translations/en/data.yml, translations/en/global_targets.yml, translations/fr/data.yml, translations/fr/global_targets.yml
=> CIF Review - Full indicator update 14.2.1

R/indicator_14-2-1.R, data/indicator_14-2-1.csv, meta/14-2-1.md
- #274 
- order percentages first in CSV so they appear as default unit
- re-organize data in CSV to improve drop-down selection behaviour
=> CIF Review - New indicator update 14.2.1 part 2

R/indicator_14-2-1.R, data/indicator_14-2-1.csv, meta/14-2-1.md, meta/fr/14-2-1.md
- #274 
- fix percentage calculation
- set 'Healthy and cautious zones', 'Canada' as data start values
=> CIF Review - Full indicator update 14.2.1 part 3

meta/11-4-1.md, meta/11-5-1.md, meta/fr/11-5-1.md, translations/en/global_targets.yml, translations/fr/global_targets.yml
https://github.com/sdg-data-canada-odd-donnees/cif-data-donnees-cic/issues/266#issuecomment-2296624731
https://github.com/sdg-data-canada-odd-donnees/cif-data-donnees-cic/issues/386#issuecomment-2296577813
=> CIF 11.5.1: Updated Target and Indicator Name

meta/11-1-1.md, meta/fr/11-1-1.md
https://github.com/sdg-data-canada-odd-donnees/cif-data-donnees-cic/issues/263#issuecomment-2299385696
=> CIF Review 11.1.1: Removed target line in the French indicator page and updated metadata fields

R/indicator_12-3-1.R, data/indicator_12-3-1.csv, meta/12-3-1.md, meta/fr/12-3-1.md, translations/en/data.yml, translations/fr/data.yml
https://github.com/sdg-data-canada-odd-donnees/cif-data-donnees-cic/issues/388#issue-2443161034
=> CIF Review 12.3.1: Updated data start values, map, translation files, and R script

meta/13-1-1.md, meta/14-2-1.md, meta/15-3-1.md, meta/fr/13-1-1.md
- #271 
- Update target wording, target line, and target in progress_calculation_options.
- Turned off automatic progress measure calculation for some problematic cases (14.2.1, 15.3.1) and set progress_status to not_available.
=> CIF Review - Target update 13.1.1

R/indicator_13-4-1.R, data/indicator_13-4-1.csv, meta/13-4-1.md, meta/fr/13-4-1.md, translations/en/global_targets.yml, translations/fr/global_targets.yml
https://github.com/sdg-data-canada-odd-donnees/cif-data-donnees-cic/issues/273#issue-2391312466
- Created metadata files
- Created R script
- Added progress measure
=> CIF Review 13.4.1: New Indicator Created

R/indicator_13-2-1.R, data/indicator_13-2-1.csv, meta/13-2-1.md, meta/fr/13-2-1.md, translations/en/data.yml, translations/fr/data.yml
=> CIF Review - Full indicator update 13.2.1

.github/workflows/refresh-indicator-data.yml, automation_helper_functions.R, meta/13-2-1.md, meta/fr/13-2-1.md
- #272 
- add "Total, all ages" as data_start_value
- turn on progress measure auto-calculation
- install dbplyr package so automated script for 13.2.1 will function as expected
=> CIF Review - Full indicator update 13.2.1 part 2

R/indicator_12-1-1.R, R/indicator_12-4-1.R, data/indicator_12-4-1.csv, meta/12-4-1.md, meta/fr/12-4-1.md, translations/en/data.yml, translations/en/global_targets.yml, translations/fr/data.yml, translations/fr/global_targets.yml
https://github.com/sdg-data-canada-odd-donnees/cif-data-donnees-cic/issues/270#issue-2391290564
**Issues solved:**
- Created metadata files
- Created R script
- Added progress measure
=> CIF Review 12.4.1: New Indicator Created

meta/11-2-1.md, meta/fr/11-2-1.md
https://github.com/sdg-data-canada-odd-donnees/cif-data-donnees-cic/issues/350#issuecomment-2307033077
=> CIF Review 11.2.1: Updated indicator description and comments and limitations

meta/13-2-1.md, meta/fr/13-2-1.md
- #272 
- add "Both sexes" as data_start_value
=> CIF Review - Full indicator update 13.2.1 review

data/indicator_3-2-1.csv, meta/3-2-1.md, meta/fr/3-2-1.md, translations/en/data.yml, translations/en/global_targets.yml, translations/fr/data.yml, translations/fr/global_targets.yml
https://github.com/sdg-data-canada-odd-donnees/cif-data-donnees-cic/issues/233
- Updated metadata files and indicator name
- Updated progress measure status
- Updated data
- Updated target
=> CIF Review 3.2.1: Updated Indicator

R/indicator_12-4-1.R, data/indicator_12-4-1.csv
https://github.com/sdg-data-canada-odd-donnees/cif-data-donnees-cic/issues/270
=> CIF Review 12.4.1: Updated R script and data

R/indicator_4-1-1.R, data/indicator_4-1-1.csv, meta/fr/4-1-1.md, translations/en/data.yml, translations/fr/data.yml
=> CIF Review - Data update 4.1.1

meta/fr/4-1-1.md
- #433 
- fix data_start_values FR
=> CIF Review - Data update 4.1.1 part 2

R/indicator_16-3-1.R, data/indicator_16-3-1.csv, translations/en/data.yml, translations/fr/data.yml
=> CIF Review - Issue with dimension names 16.3.1

meta/3-12-1.md, meta/fr/3-12-1.md
=> CIF Review - Indicator updates 3.12.1

meta/11-4-1.md, meta/15-5-1.md, meta/16-1-1.md, meta/7-3-1.md, meta/fr/1-1-1.md, meta/fr/3-6-1.md, meta/fr/3-9-1.md, meta/fr/5-1-1.md, meta/fr/5-2-1.md, meta/fr/7-3-1.md, meta/fr/9-5-1.md, translations/en/global_targets.yml, translations/fr/data.yml, translations/fr/global_targets.yml
https://github.com/sdg-data-canada-odd-donnees/cif-data-donnees-cic/issues/453
https://github.com/sdg-data-canada-odd-donnees/cif-data-donnees-cic/issues/454
https://github.com/sdg-data-canada-odd-donnees/cif-data-donnees-cic/issues/432
=> CIF Review 3.9.1, 7.3.1, and Typos: Miscellaneous Updates

meta/fr/15-6-1.md
=> CIF Review - 15.6.1 update data source

meta/2-2-1.md, meta/fr/2-2-1.md
=> CIF Review - Data source update 2.2.1

R/indicator_2-1-1.R, data/indicator_2-1-1.csv, meta/2-1-1.md, meta/fr/2-1-1.md, translations/en/data.yml
- #460 
- Manually added data for territories inside R script so it does not get overwritten by automated data updates again.
In the future, edits to territorial data for 2.1.1 must be made in the R script (cannot be edited directly in the csv).
=> CIF Review - 2.1.1 Data update

R/indicator_2-1-1.R, data/indicator_2-1-1.csv, meta/2-1-1.md, meta/fr/2-1-1.md
- #460 
- Add new 2022 data for territories
=> CIF Review - 2.1.1 data update part 2

data/indicator_11-1-1.csv, meta/11-1-1.md, meta/fr/11-1-1.md
https://github.com/sdg-data-canada-odd-donnees/cif-data-donnees-cic/issues/468#issue-2505567728
=> CIF Review 11.1.1: Updated Graph Type and Unit of Measure

meta/12-1-1.md, meta/fr/12-1-1.md
=> CIF Review - 12.1.1 Data source update

R/indicator_2-1-1.R, data/indicator_2-1-1.csv, translations/en/data.yml, translations/fr/data.yml
- #460 
- Remove "All persons" data from demographic characteristics that duplicates the "All persons" data in economic family types
- Add missing FR translations for demographic characteristics categories
=> CIF Review - 2.1.1 Data update review

R/indicator_12-2-1.R, data/indicator_12-2-1.csv, meta/12-2-1.md, meta/fr/12-2-1.md, translations/fr/data.yml
- #474 
- fixed headline data in R script and csv to correct data not displaying issue
- set data_start_values
- added missing FR data translation and edited some others for consistency
=> CIF Review - 12.2.1 Fix data

R/indicator_5-4-1.R, data/indicator_5-4-1.csv, meta/5-4-1.md, meta/fr/5-4-1.md, translations/en/data.yml, translations/fr/data.yml
=> CIF Reivew - 5.4.1 Data update

R/indicator_1-1-1.R, R/indicator_4-1-1.R, automation_helper_functions.R, data/indicator_11-2-1.csv, data/indicator_11-4-1.csv, data/indicator_12-1-1.csv, data/indicator_16-1-1.csv, data/indicator_5-2-1.csv, data/indicator_5-4-1.csv
- update some data locally
- speedup package installation for data updates
- more verbosity for testing
=> Data update fixes

automation_script.R
=> Manual override: stop data updates for bad indicators

R/indicator_5-4-1.R, data/indicator_5-4-1.csv, meta/5-4-1.md, meta/fr/5-4-1.md
- #469 
- align sex categories from archived source to gender categories in new source
- add comment in metadata about sex/gender alignment
=> CIF Review - 5.4.1 Data update part 3

R/indicator_5-4-1.R, data/indicator_5-4-1.csv
- #469 
- only keep 2015 data that are disaggregated by one dimension at a time
=> CIF Review - 5.4.1 Data update review

R/indicator_11-2-1.R, data/indicator_11-2-1.csv, meta/11-2-1.md, meta/fr/11-2-1.md, translations/en/data.yml, translations/fr/data.yml
=> CIF Review - 11.2.1 Data update

meta/6-5-1.md, meta/6-6-1.md, meta/fr/6-5-1.md, meta/fr/6-6-1.md
add source url 6.5.1/6.6.1 (#252, #347)
=> CIF Review - 6.5.1/6.6.1 review

data/indicator_15-4-1.csv
- #221 
- add 2021 provincial/territorial data 15.4.1
=> CIF Review - 15.4.1 Data update

meta/11-2-1.md, meta/fr/11-2-1.md
- #483 
- data_start_value correction
=> CIF Review - 11.2.1 Data update part 4

meta/11-3-1.md, meta/12-1-1.md, meta/14-1-1.md, meta/15-4-1.md, meta/15-5-1.md, meta/16-2-1.md, meta/17-1-1.md, meta/3-1-1.md, meta/3-14-1.md, meta/3-3-1.md, meta/5-2-1.md, meta/fr/14-1-1.md, meta/fr/15-4-1.md, meta/fr/5-2-1.md
- #473
- turn on auto progress measure calculations:
- 3.1.1
- 3.14.1
- 15.5.1
- 16.2.1
- 17.1.1
- manually set progress measure as not_available: 3.3.1
- add targets: 5.2.1
- update progress calculations options: 11.3.1 and 12.1.1
- add target line: 14.2.1 and  15.4.1
=> CIF Review - Progress measure

meta/4-3-1.md
- #473 
- change direction of progress calculation 4.3.1
=> CIF Review - Progress measure part 2

meta/11-3-1.md, meta/13-1-1.md, meta/13-3-1.md, meta/14-1-1.md, meta/14-2-1.md, meta/15-1-1.md, meta/15-2-1.md, meta/15-3-1.md, meta/15-4-1.md, meta/15-5-1.md, meta/15-6-1.md, meta/17-2-1.md, meta/3-10-1.md, meta/3-12-1.md, meta/6-4-1.md, meta/8-4-1.md, meta/fr/11-3-1.md, meta/fr/13-1-1.md, meta/fr/13-3-1.md, meta/fr/14-1-1.md, meta/fr/15-1-1.md, meta/fr/15-2-1.md, meta/fr/15-4-1.md, meta/fr/17-1-1.md, meta/fr/17-3-1.md, translations/en/global_targets.yml, translations/fr/data.yml, translations/fr/global_targets.yml
=> Cif Review - Typos

meta/3-14-1.md, meta/fr/3-14-1.md
- #473
- add note warning that progress status is not displayed because there is not enough data 3.14.1 en/fr
=> CIF Review - progress measure part 3

meta/5-1-1.md, meta/fr/5-1-1.md
https://github.com/sdg-data-canada-odd-donnees/cif-data-donnees-cic/issues/491
=> CIR Review 5.1.1: Headline Data Updated

data/indicator_9-4-1.csv
https://github.com/sdg-data-canada-odd-donnees/cif-data-donnees-cic/issues/214
=> CIF Review 9.4.1: Updated 9.4.1's CSV with CTRC data

translations/en/data.yml, translations/fr/data.yml
- #468 
- add missing FR translation for percent change since 2016 unit
=> CIF Review - 11.1.1b review

R/indicator_12-4-1.R, data/indicator_12-4-1.csv, meta/12-4-1.md, meta/fr/12-4-1.md
- #270 
- update denominator for percentage of plastic leakage calculation in R script according to directions from SME
- update metadata with new information on the indicator calculation
=> CIF Review - 12.4.1 review

R/indicator_3-13-1.R, data/indicator_3-13-1.csv, meta/3-13-1.md
- #244 
- added progress_calculation_options for target and target_year for 3.13.1
- R script now has a filter that only keeps data from complete years
=> CIF Review - 3.13.1 progress calc opts, incomplete year filtering

meta/3-13-1.md
- #244 
- turn off automatic progress calculation and set progress_status: deterioration due to bug affecting the output of the automatic progress calculation
=> CIF Review - 3.13.1 - progress calculation manual override

meta/16-1-1.md
=> CIF Review - 16.1.1 Typo

translations/en/header.yml, translations/fr/header.yml
=> CIF Review - Remove user notice

meta/5-2-1.md, meta/fr/5-2-1.md
=> CIF Review - 5.2.1 Wrong target

translations/fr/frontpage.yml
=> CIF Review - misc.update FR content

translations/fr/menu.yml
- #524 
- update link text for cookies page on FR homepage to: Cookies (en anglais seulement)
=> edit cookies link text

R/indicator_9-6-1.R, data/indicator_9-6-1.csv
Filter out data for future years.
=> 9.6.1 bugfix

ProgressMeasure.py, R/indicator_3-13-1.R, data/indicator_3-13-1.csv, translations/en/status.yml, translations/fr/status.yml
- Specified the name of the file within the archive to pull data from.
=> 3.13.1 script maintenance

R/indicator_5-3-1.R, R/indicator_5-5-1.R, R/indicator_8-1-1.R, R/indicator_8-2-1.R, R/indicator_8-4-1.R, meta/8-1-1.md, meta/8-2-1.md, meta/8-4-1.md, meta/fr/8-1-1.md, meta/fr/8-2-1.md, meta/fr/8-4-1.md, translations/en/data.yml, translations/fr/data.yml
update automation scripts, metadata, and sources following latest LFS revisions
=> LFS update

R/indicator_11-7-1.R, R/indicator_3-1-1.R, R/indicator_3-14-1.R, R/indicator_3-6-1.R, R/indicator_3-7-1.R, R/indicator_3-8-1.R, data/indicator_11-7-1.csv, data/indicator_3-1-1.csv, data/indicator_3-14-1.csv, data/indicator_3-6-1.csv, data/indicator_3-7-1.csv, data/indicator_3-8-1.csv, meta/11-7-1.md, meta/3-1-1.md, meta/3-14-1.md, meta/3-6-1.md, meta/3-7-1.md, meta/3-8-1.md, meta/fr/11-7-1.md, meta/fr/3-1-1.md, meta/fr/3-14-1.md, meta/fr/3-6-1.md, meta/fr/3-7-1.md, meta/fr/3-8-1.md
https://github.com/sdg-data-canada-odd-donnees/cif-data-donnees-cic/issues/492#issue-2523228004
=> Updated indicators with new CCHS data tables

data/indicator_15-2-1.csv, data/indicator_3-10-1.csv, meta/3-10-1.md, meta/fr/3-10-1.md
=> More manual updates - 3.10.1, 15.2.1

meta/3-12-1.md, meta/fr/3-12-1.md, translations/fr/data.yml
Temporarily removing 3.12.1 data
=> Temp data removal 3.12.1

R/indicator_11-4-1.R, data/indicator_11-4-1.csv, meta/11-4-1.md, meta/6-5-1.md, meta/6-6-1.md, meta/fr/11-4-1.md, meta/fr/6-5-1.md, meta/fr/6-6-1.md, translations/en/data.yml, translations/fr/data.yml
- #534 
- #557 
- Update 11.4.1 script, data, and metadata for new CODR
=> 6.5.1, 6.6.1, 11.4.1

meta/11-4-1.md, meta/fr/11-4-1.md
- #557 
- Update source to new CODR
=> 11.4.1 new source

data/indicator_6-2-1.csv, meta/6-2-1.md, meta/fr/6-2-1.md, translations/en/data.yml, translations/fr/data.yml
=> update data 6.2.1

R/indicator_11-4-1.R, R/indicator_13-3-1.R, data/indicator_13-3-1.csv, meta/13-3-1.md, meta/fr/13-3-1.md, meta/fr/6-2-1.md, translations/en/data.yml, translations/fr/data.yml
- #563
- #565
- Point fr source link to fr page
=> automate and update 13.3.1

R/indicator_13-3-1.R, data/indicator_13-3-1.csv, translations/en/data.yml, translations/fr/data.yml
=> 13.3.1 municipality types translations

R/indicator_7-2-1.R, data/indicator_7-2-1.csv
=> remove last ref year if incomplete 7.2.1

meta/13-3-1.md, meta/fr/13-3-1.md
=> add limitation note 13.3.1

meta/3-10-1.md, meta/3-11-1.md, meta/3-5-1.md, meta/5-3-1.md, meta/fr/3-10-1.md, meta/fr/3-11-1.md, meta/fr/3-5-1.md, meta/fr/5-3-1.md
Correct spelling mistakes in banner for multi-series indicators en/fr
=> correct multi-series banner en/fr

meta/11-4-1.md, meta/fr/11-4-1.md
=> add limitations note 11.4.1

.github/workflows/refresh-indicator-data.yml
Only attempt to commit new data from update workflow if files haves been modified.
=> commit only when new data is available

automation_script.R
Fix scoping by making list of skipped indicators a global variable.
=> bugfix for list of skipped indicators

translations/en/frontpage.yml, translations/fr/frontpage.yml
=> link to new GIF hub

meta/3-12-1.md, meta/fr/3-12-1.md
=> change geographical area and headline label to Inuit Nunangat

data/indicator_9-4-1.csv
=> fix duplicate year 9.4.1

_prose.yml, meta/11-4-1.md, meta/fr/11-4-1.md, translations/en/status.yml, translations/fr/status.yml
Set 11.4.1 reporting status as not available
=> 11.4.1 not available

R/indicator_11-4-1.R, R/indicator_11-5-1.R, R/indicator_3-13-1.R
- 3.13.1: Bugfix related to filtering on a non-existant column. Add data disaggregated by sex.
- 11.4.1: Temporarily skip this indicator while the source data is under review
- 11.5.1: Add automation for 2021 data
=> R script bugfixes for several indicators

R/indicator_3-9-1.R, data/indicator_3-9-1.csv, meta/3-9-1.md, meta/fr/3-9-1.md, translations/fr/data.yml
- #473 
- Add automated progress status for 3.9.1 with notes in metadata
- Fix fr translations for some vaccines
- Update data_start_values to show all recommended vaccines for 2 years olds (as used in the progress measure)
=> Progress measure 3.9.1

meta/3-9-1.md, meta/fr/3-9-1.md
- #473 
- Better wording for 3.9.1 metadata
=> metadata wording improvement 3.9.1
